### ISSUE TITLE
Set minimum file size to be downloaded with Persepolis

### ISSUE THREAD

**Issue by salahoued** [persepolisdm/Persepolis-WebExtension#11]
Hello,
In the Firefox's plug-in section I had read that PDM browser integration is a fork of ```uget-chrome-wrapper```, and in this extension there is an option to set the minimum file size that will be downloaded with PDM, to put it simple if the file to be downloaded has a size less than the file size set by the user this extension will not interrupt download and the file will be downloaded within the browser.

I would like to see it in PDM's browser integration, for me if the file size is less 5-10M there no need to be downloaded with an external DM.

Thanks :)

**Comment by JafarAkhondali** [comment]
Hi,
Actually I've changed that fork a lot and the mechanism is kinda differnt now, But we'll absolutely add this feature in next version.
Thanks 👍

**Comment by salahoued** [comment]
That's really nice,
Thanks a lot
