### ISSUE TITLE
Doesn't work with Vivaldi

### ISSUE THREAD

**Issue by Noruas29** [persepolisdm/Persepolis-WebExtension#13]
Persepolis is started.
Webextension is installed and available.
Try to download something, integrate downloader of Vivaldi appear and download the file... Persepolis never show anything.
Try with different file format, same result.

**Comment by alireza-amirsamimi** [comment]
Hello
What is your operating system? 
Do you use the latest version of persepolis?

**Comment by Noruas29** [comment]
Try it on last Windows 10 and Windows 8.1, same result.
Yes, it is the last one.

**Comment by Nirose** [comment]
I've tried on the latest Vivaldi. It doesn't intercept downloads, but it works with context menu option.

**Comment by JafarAkhondali** [comment]
@Noruas29 @Nirose Sorry for late response
Vivaldi used Chromium engine but changed it's download method to Firefox way (It means it'll ask user to download file unlike Chromium that downloads the file automatically)
So it took a while for me to find the problem. The patch will be available in next release I'll notify you when it's done.

**Comment by JafarAkhondali** [comment]
Added in version 1.9.0

**Comment by Nirose** [comment]
Thanks a lot. have a great evening

Sent from ProtonMail mobile

-------- Original Message --------
