### ISSUE TITLE
Automatically starts the download manager even if disabled

### ISSUE THREAD

**Issue by Doc73** [persepolisdm/Persepolis-WebExtension#14]
In my system (Debian Stretch AMD64, with Firefox Stable), I usually keep the extension disabled (by Ctrl + Shift + U).
However, the first time I start a download in a sessione, the Firefox download manager is launched first, then also Persepolis. The second time, the Firefox download manager works regularly.
It's very annoying.
Thank you very much in advance.

**Comment by JafarAkhondali** [comment]
Fixed in version 1.9.0
