### ISSUE TITLE
/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by TassdarZeratul** [persepolisdm/Persepolis-WebExtension#16]
![image](https://user-images.githubusercontent.com/29266528/47362855-fb8f1000-d707-11e8-944c-e2d9ead2e0a4.png)

**Comment by JafarAkhondali** [comment]
@TassdarZeratul :smile: 
I'll create a better shortcut for next version

**Comment by JafarAkhondali** [comment]
Added in version 1.9.0
