### ISSUE TITLE
Option to remove from context menu

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [persepolisdm/Persepolis-WebExtension#18]
Hi, I use Persepolis and i think its good idea to extension for Disable/Remove extension entry (Download all links with Persepolis) from context menu.
Thanks

**Comment by JafarAkhondali** [comment]
Hey, Thanks for your opinion. What makes you think that removing this option is helpful? I use it sometimes and other DLs extension have this option as well.

**Comment by JafarAkhondali** [comment]
@AmirHosseinKarimi Ok i'll add this option for next version

**Comment by JafarAkhondali** [comment]
@AmirHosseinKarimi Added in version 1.9.0
