### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by FFV47** [persepolisdm/Persepolis-WebExtension#19]
Extension it's not working at all after update, it doesn't interrupt downloads and context menu is missing, I tried reinstalling but it remains the same. It was working fine before the update. I'm on Linux and I use the extension on chromium if that matters.

**Comment by Elanzer47** [comment]
Just checked, I'm on 1.9.2 and context menu still missing ( it's enabled on config). it's only me??

**Comment by JafarAkhondali** [comment]
Sorry looks like this bug occurs after browser restart.
Can you update to 1.9.3 and tell if it exists?
I've tested it several times now ( as the developers say it work on my machine :smile:  )
