### ISSUE TITLE
cannot use it together with a custom firefox user.js file (hardned for security)

### ISSUE THREAD

**Issue by m040601** [persepolisdm/Persepolis-WebExtension#20]
Hi, thank you for your work in this extension. 
I know this might not be the right place to ask this question. 
I have no problems using this extension on a standard non customized Firefox profile. It even works perfectly fine together with other aggressive javascript/adblockers extensions. etc.

I'm also trying to use a custom user.js file on my firefox profile.
As you may know this is done to customize your firefox in a more "aggressive" and "permanent" way than just using the user interface.
It changes a lot of other hidden preferences.

I' using this one, https://github.com/pyllyukko/user.js.
There is some change being done to the firefox preferences, that makes it impossible to use persepolis the extension.

I've already tried searching and toggling through these various changed options, to pinpoint exactly what could it be. Described the issue here, https://github.com/pyllyukko/user.js/issues/453.

Would you have any tips or idea for which changed firefox preference could be impacting Persepolis ? Thanks in advance

**Comment by m040601** [comment]
I think I'm making some progress here:

>  To find more about problem:
>     Go to about:debugging
>     Mark Add-on debugging
>     Click on Debug button of "Persepolis Download Manager Integration"
>     Then try to use addon and download something, if anything went wrong an error should appear in console tab of debug area
> 

I did that. And then I caught this error message on the "console tab" of the main window of developer tools. ( Not the "console tab" of the "debug tab" ?)

**Comment by JafarAkhondali** [comment]
What is the error?!

**Comment by m040601** [comment]
updated my previous comment

**Comment by m040601** [comment]
Update on the  "Persopolis user interface problem" part
Please ignore that previous part of my comment.
I restarted Persepolis, and everything seems to be working fine again, as it is supposed to be (on the GUI interface).

Apollogies for the confusion.

**Comment by m040601** [comment]
Did some quick research on this "first party isolation" thing of Firefox. 

1. 2018, https://www.ctrl.blog/entry/firefox-fpi

> First-Party Isolation is a fundamental change....breaks many assumptions made by web developers. If you want to enable the feature and gain better privacy than you also have to pay the price of breaking those assumptions.

2. 2018, https://www.maketecheasier.com/first-party-isolation-firefox/

> ... seems like it’ll be a permanent feature in Firefox, but few people are aware of it....

Again, I'm not a developer, and apologies if I'm missing something here not obvious.

But could you clarify (?docs) what is it about the persepolis extension that makes it incompatible with setting this privacy preference in Firefox ?

**Comment by JafarAkhondali** [comment]
It's my first time hearing about 'first-party-isolation'. Some actions like download need authentication to server. Cookies are pieces of text that can handle authentication in browsers. So when Persepolis wants to download something, it needs cookies too. Persepolis extension sends cookies along download links and that might cause a problem with 'first-party-isolation' because cookies are really important.

Thanks for your feedback, please close the issue when your problem is solved :+1:

**Comment by m040601** [comment]
yeah, these kind of "experimental" and "aggressive" browser settings,
keep changing fast and being created by Mozzila at an incredibe and difficult to 
keep up pace with.

So conclusion, dont set
user_pref("privacy.firstparty.isolate",	true);
if you want to use Persepolis.

Thanks for your attention to this issue.
