### ISSUE TITLE
Persepolis will be closed after adding new downloads

### ISSUE THREAD

**Issue by morealaz** [persepolisdm/Persepolis-WebExtension#22]
After adding new download by web extension, persepolis will be closed instead of being active with no error.

**Comment by JafarAkhondali** [comment]
@morealaz Hey, this is a problem with Persepolis itself, not extension. We are working on this

**Comment by alireza-amirsamimi** [comment]
@morealaz 
Hello
Please install persepolis-git from aur again and tell me the result.
What is you desktop environment and your browser?

**Comment by alireza-amirsamimi** [comment]
Please tell me the results in persepolis issue. I think It's related to persepolis and not web extension.

**Comment by morealaz** [comment]
Hi,
After recent Persepolis updates this issue has been solved. thanks.
