### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by amirarabsalmani** [persepolisdm/Persepolis-WebExtension#23]
Hi there
perspolis extension is not working either on opera or chromium. everything seems ok but when i click on an url or any download link, it justs won't work.

**Comment by JafarAkhondali** [comment]
Hello,
Is the extension active? Check it in pop-up menu. Icon should be red.
Are Persepolis and Extension updated?

**Comment by amirarabsalmani** [comment]
yes, as i said every thing seems totally fine, but nothing happen when i click on a download link. both version is the latest update.

**Comment by JafarAkhondali** [comment]
That's weird! It have to do something with the bridge file. What is the output of this command?
`cat ~/.config/chromium/NativeMessagingHosts com.persepolis.pdmchromewrapper.json`

**Comment by amirarabsalmani** [comment]
I really appreciate your help.
This is output:
{"name": "com.persepolis.pdmchromewrapper", "type": "stdio", "path": "/home/amir/.config/persepolis_download_manager/persepolis_run_shell", "description": "Integrate Persepolis with opera using WebExtensions", "allowed_origins": ["chrome-extension://legimlagjjoghkoedakdjhocbeomojao/"]}

**Comment by DanielValahul** [comment]
I have the same problem on Firefox 71/ Fedora 31. The extension doesn't work

**Comment by JafarAkhondali** [comment]
@DanielValahul for Firefox, the path is different. Try this one:
`cat ~/.mozilla/native-messaging-hosts/com.persepolis.pdmchromewrapper.json`

**Comment by DanielValahul** [comment]
Now it does output something, but the extension still doesn't work. 

`{"name": "com.persepolis.pdmchromewrapper", "type": "stdio", "path": "/home/zalmoxis/.config/persepolis_download_manager/persepolis_run_shell", "description": "Integrate Persepolis with firefox using WebExtensions", "allowed_extensions": ["com.persepolis.pdmchromewrapper@persepolisdm.github.io", "com.persepolis.pdmchromewrapper.offline@persepolisdm.github.io"]}`

**Comment by JafarAkhondali** [comment]
@DanielValahul Ok so if you execute this:
`/home/zalmoxis/.config/persepolis_download_manager/persepolis_run_shell`
it should run persepolis (if not already running).

If this doesn't work, tell me the errors here.
If persepolis runned, then extension is the cause of problem. Try to download a file directly by right clicking a link and  "Download with Persepolis" in context menu.

If possible, try to check the logs of extension from here:
Go to about:debugging, then find "Persepolis Download Manager Integration". And select debug

**Comment by DanielValahul** [comment]
```
Could not map contract ID '@mozilla.org/sharepicker;1' to CID {1201d357-8417-4926-a694-e6408fbedcf8} because no implementation of the CID is registered.
Content Security Policy: Couldn't parse invalid host 'wasm-eval'
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Getting Key:pdm-interrupt ::  true background.js:438:13
Getting Key:context-menu ::  null background.js:438:13
Value Is NuLL:context-menu ::  true background.js:441:17
Getting Key:keywords ::  null background.js:438:13
Value Is NuLL:keywords ::  background.js:441:17
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. extension.html
unreachable code after return statement 2 background.js:1288:12
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. update.js:26
    schedule moz-extension://345e59e2-0915-40c2-a281-116191303d9b/include/update.js:26
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. extension.js:113
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1507
Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. 140 ExtensionUtils.jsm
Request to access cookie or storage on “https://api.bitwarden.com/sync” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. background.html
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. IndexedDB.jsm:120:34
Error: An unexpected error occurred ExtensionUtils.jsm
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1507

```
It appears there are some errors

**Comment by DanielValahul** [comment]
The extension doesn't work, app is fine.

I couldn't find much debugging info. 

```

Getting Key:pdm-interrupt ::  true background.js:438:13
Getting Key:context-menu ::  null background.js:438:13
Value Is NuLL:context-menu ::  true background.js:441:17
Getting Key:keywords ::  null background.js:438:13
Value Is NuLL:keywords ::  background.js:441:17
```

**Comment by JafarAkhondali** [comment]
@DanielValahul Please try to download a file and see if there is anything else in debugging infos

**Comment by DanielValahul** [comment]
I tried, there is nothing.

**Comment by DanielValahul** [comment]
Well I observed a new issue, which I think it's related. After I installed the extension I got this message
```
persepolis quit unexpectedly
The application encountered a problem and could not continue.
```

This is reproducible: if i close the broswer, open persepolis, and reopen the browser, the issue will pop up again
