### ISSUE TITLE
 Persepolis Extension is not work

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/Persepolis-WebExtension#25]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): ubuntu 19.04
* Desktop Environment(For GNU/Linux and BSD users): BSPWM
* Persepolis Version: 3.2.0
* How do you install Persepolis? Repositories

hi
I install Persepolis Extention on Brave browser but the Extention not working
is it necessary to active specific service in BSPWM?
[BSPWM](https://github.com/baskerville/bspwm)

**Comment by JafarAkhondali** [comment]
Hey @Monirzadeh 
Currently we are not officially support Brave browser. But as a work around, you can make it work by adding an specific native host. Create a file in `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json`
```
{"name": "com.persepolis.pdmchromewrapper", "type": "stdio", "path": "/home/black-hole/.config/persepolis_download_manager/persepolis_run_shell", "description": "Integrate Persepolis with chromium using WebExtensions", "allowed_origins": ["chrome-extension://legimlagjjoghkoedakdjhocbeomojao/"]}
```

We'll fix it in next version.

**Comment by Monirzadeh** [comment]
hi @JafarAkhondali 
I do that but it does not work for me

**Comment by JafarAkhondali** [comment]
@Monirzadeh Sorry updated the code. You'll need to replace YOUR_USERNAME with yours.

**Comment by Monirzadeh** [comment]
> @Monirzadeh Sorry updated the code. You'll need to replace YOUR_USERNAME with yours.

thanks, it is fixed
I fix manualy please add brave support in next release

**Comment by JafarAkhondali** [comment]
@Monirzadeh ok sure.
