### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by fabianskibr** [persepolisdm/Persepolis-WebExtension#26]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): KDE Neon
* Desktop Environment(For GNU/Linux and BSD users): Plasma
* Persepolis Version: 3.2.0
* Persepolis Firefox Extension Version: 2.2.0
* How do you install Persepolis? persepolis/ppa

It's not working. When I click on a file link to download the persepolis download window does not open.

The extension also breaks the downloads the download manager of firefox, they do not start. If I disable it downloads work normally.

I recorded a video showing both problems.

 https://youtu.be/cWXBoF7Vrz4

**Comment by JafarAkhondali** [comment]
Did this make the extension work?
We need cookies to download files, i can make it work without cookies (for grabbing link without cookies) later. But not sure if this is a good idea

**Comment by fabianskibr** [comment]
Yes. Disabling this the extension work fine.
It would be great if you could make it work without using cookies.

**Comment by JafarAkhondali** [comment]
Sure, i'll add it to next release.

**Comment by culebrasolida** [comment]
not working for me tho, using persepolis 3.2.0 and firefox extension from firefox addons website, installed it today, persepolis is not grabbing my downloads.
