### ISSUE TITLE
Can't download IPSWs from apple

### ISSUE THREAD

**Issue by PlanetAaron** [persepolisdm/Persepolis-WebExtension#31]
When trying to download an IPSW from apple's servers on firefox, it goes to firefox's download manager instead and then it fails. Adding .ipsw to exclude urls containing makes it work through the native download manager. I don't know if this is limited to Apple's servers, IPSWs on Apple's servers, or IPSWs in general. 

Here's the iPadOS 13.3.1 IPSW for iPad gen 7 for an example of what isn't working. 
[http://updates-http.cdn-apple.com/2020WinterFCS/fullrestores/061-40122/0E8D0B9B-93F2-4A56-9D11-970B9E03ADD7/iPad_Educational_13.3.1_17D50_Restore.ipsw](url)

I did also test it with the iOS 7.1.2 IPSW for iPhone 4 GSM and it was the same issue. Here's a link to that in case you want to use it for reference too.
[http://appldnld.apple.com/iOS7.1/031-4812.20140627.cq6y8/iPhone3,1_7.1.2_11D257_Restore.ipsw](url)

Manually adding these links in the GUI seems to work.

Sorry the description was blank earlier, I accidentally hit submit too soon.

**Comment by JafarAkhondali** [comment]
@PlanetAaron I tried it and it worked fine. Does your DM work well with other downloads? Can you provide an error \ video for it? Are you sure there is enough space to download?

If the extension opens the Persepolis modal, then the problem is with Persepolis itself.

**Comment by PlanetAaron** [comment]
So apparently it’s because the browser plugin wasn’t working right. I guess my aria2 config was causing issues
