### ISSUE TITLE
persepolisdm not integrated with brave

### ISSUE THREAD

**Issue by Javi3y** [persepolisdm/Persepolis-WebExtension#46]
i'm using brave web browser and I've installed the extension and it's on
when i download something with my browser it doesn't download that is a good sign i guess because it shows that the extension is working but persepolisdm isn't opening
I've tried it with both persepolis opened and closed but it still doesn't work

**Comment by Javi3y** [comment]
this is the extensions id = legimlagjjoghkoedakdjhocbeomojao

**Comment by JafarAkhondali** [comment]
Please see the pinned issue: https://github.com/persepolisdm/Persepolis-WebExtension/issues/25

**Comment by Javi3y** [comment]
thanks a lot
love from Iran <3
