### ISSUE TITLE
Firefox extension dont work in Librewolf (Linux)

### ISSUE THREAD

**Issue by Milor123** [persepolisdm/Persepolis-WebExtension#59]
Interrup Downloads is ON
and Context Menu ON

I try download files from https://myjob.page/tools/test-files

I've tried change `privacy.firstparty.isolate` settings to `false`, and all related but nothing work, persepolis dont detect the file

I have all as default  in persepolis and it is in the system tray
![image](https://github.com/persepolisdm/Persepolis-WebExtension/assets/14153649/af3156f0-bc4e-4587-a838-294e9045c7a6)

What should I do guys?

In Vivaldi it work correctly, but not in firefox (Librewolf)

**Comment by JafarAkhondali** [comment]
Hello @Milor123 ,
Current published extension is ~3 years old, actually I expected it to stop working earlier :)
We are working on updating it with manifest version 3 standard  (branch `manifest-version-3`)  and fix known issue, it'll take some time to sync it with new version of the Persepolis across different platforms.

**Comment by Milor123** [comment]
Thank you very much, we will be waiting for the new update, a hug !

**Comment by Milor123** [comment]
For now it solve my problem https://github.com/persepolisdm/persepolis/issues/966#issuecomment-2041086784
