### ISSUE TITLE
Persepolis does not open by clicking on the download link

### ISSUE THREAD

**Issue by thmkhtry** [persepolisdm/Persepolis-WebExtension#62]
Hello,
When I click on the download link in the Firefox browser, the extension does not work to open Persepolis.
I have Fedora Linux distribution installed and the latest version of Persepolis and plugins are also installed.

**Comment by alireza-amirsamimi** [comment]
Hello
What is your desktop environment?
What if you open Persepolis before clicking on the link?

**Comment by thmkhtry** [comment]
I have gnome desktop.
In that case, the file will be downloaded well with Persepolis

**Comment by thmkhtry** [comment]
Solved with enable "Access your data for all websites" in `Manage Extension > Permissions` and enable "Run on sites with restrictions" in `Manage Extension > Details`
