### ISSUE TITLE
Doesn't work with Persepolis Download Manager v5.0.0

### ISSUE THREAD

**Issue by MF-Debug** [persepolisdm/Persepolis-WebExtension#63]
Please make this work with the new version. Thanks.

Edit: I'm using latest Firefox Nightly build on Windows 10 x64.

**Comment by alireza-amirsamimi** [comment]
Please test stable release of Firefox and tell me the result. The Nightly builds are not stable.

**Comment by MF-Debug** [comment]
> Please test stable release of Firefox and tell me the Nightly builds are not stable.

Just tested, it also doesn't work with stable Firefox v130.0

**Comment by alireza-amirsamimi** [comment]
Thank you. Do you test [this](https://github.com/persepolisdm/Persepolis-WebExtension/issues/62)?

**Comment by alireza-amirsamimi** [comment]
![image](https://github.com/user-attachments/assets/88771e8c-69fa-4bd6-a4d4-af1d9719d78c)

**Comment by MF-Debug** [comment]
> Thank you. Do you test [this](https://github.com/persepolisdm/Persepolis-WebExtension/issues/62)?

I enabled it, but it still doesn't work. Restarted both browser and app after enabling this option.

**Comment by alireza-amirsamimi** [comment]
I will definitely check on Windows OS and let you know the result.

**Comment by mostafaasadi** [comment]
@MF-Debug Hello
I tested this and it works like a charm!
persepolis 5.0
firefox 129.0.2 (64-bit) 
windows 11

**Comment by kiahamedi** [comment]
Hello Dear @MF-Debug 
i tested version 5.0.0 with last version extension and its works for **Interrupt downloads** and **Context Menu** stage.

**Comment by alireza-amirsamimi** [comment]
@MF-Debug 
Do you enable extension?
![Screenshot_%Y%M%D_%H%m%S](https://github.com/persepolisdm/persepolis/assets/7452500/2f3916c9-73d8-40ec-a87d-53475afaa056)

**Comment by MF-Debug** [comment]
> @MF-Debug Do you enable extension? ![Screenshot_%Y%M%D_%H%m%S](https://private-user-images.githubusercontent.com/7452500/336143505-2f3916c9-73d8-40ec-a87d-53475afaa056.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTkyOTEsIm5iZiI6MTcyNjE5ODk5MSwicGF0aCI6Ii83NDUyNTAwLzMzNjE0MzUwNS0yZjM5MTZjOS03M2Q4LTQwZWMtYTg3ZC01MzQ3NWFmYWEwNTYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDM0MzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjMTMwMjAwMGVjY2U2NWMwMzkxZGI3YzcxZGFjNGY2MDk0Y2RmNTNkOWNjZThiNjJmYmEyODRjZDIyOTQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nhYlKlrtF2tgihIP7cezGPPZlqdE25wzzN6Ni3QdVO4)

I completely missed this, now it's working! Thanks!
