### ISSUE TITLE
Save as does not work when extension enabled

### ISSUE THREAD

**Issue by offhub** [persepolisdm/Persepolis-WebExtension#7]
Hi,

Whenever l right click 'Save image/link as...' it does nothing while extension enabled. It works if I disable extension or when pressing shortcut key (Insert).

Thanks

Win7 x64
Chrome 61/62
Persepolis Download Manager Integration 1.5.1

**Comment by JafarAkhondali** [comment]
@offhub Hi, thanks for report. I test the behavior and it worked for images, but ignored links and allowed browser to handle the downloading of page. What version of Perseplis are you using? Is this problem happend recently? If yes, what did you do? Can you provide some examples of this situation?

**Comment by offhub** [comment]
Isn't it possible to ignore all save as actions from persepolis and allow browser to handle them?

**Comment by JafarAkhondali** [comment]
@offhub I ignore any saving operation and redirect it to Persepolis, but looks like Chrome doesn't let me ignore webpages, since webpages need more download requests for images, css files etc. But downloading images works fine for me, Can you provide an example?

**Comment by offhub** [comment]
Sorry! Apparently, "Persepolis Download Manager 2.4.2" was not running earlier.

What I mean/want is:

When I right click and select "save image as" then it should be handled by browser not by manager.

**Comment by JafarAkhondali** [comment]
@offhub The default behavior is handle everything, But if you want this behavior just click on add-on icon in browser, then add this string in text input:
jpg,jpeg,png,gif,webp,svg
and then hit "Save" and try again saving. If your problem solved please close the issue, thanks
