### ISSUE TITLE
It doesn't work on Ubuntu 16.04 and Chrome

### ISSUE THREAD

**Issue by arg1998** [persepolisdm/Persepolis-WebExtension#8]
I've installed the latest version of Persepolis software and its integration extension on chrome.
but the extension doesn't send the link to software for download.
please fix it.

**Comment by arg1998** [comment]
sorry for delay , this is the content of that file you asked for:


{
    "description": "Integrate Persepolis with chrome using WebExtensions",
    "path": "/usr/bin/persepolis",
    "allowed_origins": [
        "chrome-extension://legimlagjjoghkoedakdjhocbeomojao/"
    ],
    "type": "stdio",
    "name": "com.persepolis.pdmchromewrapper"
}

**Comment by JafarAkhondali** [comment]
Please wait for our new release, It shouldn't take long.

**Comment by JafarAkhondali** [comment]
@arg1998 Please update your Persepolis and Browser add-on to latest version, It should work now.

**Comment by JafarAkhondali** [comment]
I'll close the issue since there is no response from you, Feel free to reopen it.
