### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by MisterGlasses** [persepolisdm/Persepolis-WebExtension#9]
![image](https://user-images.githubusercontent.com/27768847/33664880-15237ff4-dad0-11e7-85ed-ff917d8d215f.png)
I installed pdm ant its chrome extension,but when I used the right-click "Download with pdm", it remind me this. what's this and what should I do?

**Comment by JafarAkhondali** [comment]
Hello, Sorry about the error, We are working on this error and will let you know when it's fixed.

**Comment by JafarAkhondali** [comment]
@MisterGlasses Please update your Extension to(1.7.1) and PDM to 3.0.+. This bug has been fixed.

**Comment by JafarAkhondali** [comment]
I'll close the issue since there is no response from you, Feel free to reopen it.
